export const APP_ENV = DOT_ENV;
export const MCT_ROOT = APP_ENV.REACT_MCT_ROOT;
export const BASE_PATH = APP_ENV.REACT_BASE_PATH;
export const MCT_API_BASE = APP_ENV.REACT_MCT_API_BASE;
export const APP_CLUSTER = APP_ENV.REACT_APP_CLUSTER;

export const MORALIS_API_KEY = APP_ENV.REACT_MORALIS_API_KEY;