export const APP_ENV = DOT_ENV;
export const MCT_ROOT = APP_ENV.REACT_MCT_ROOT;
export const BASE_PATH = APP_ENV.REACT_BASE_PATH;
export const MCT_API_BASE = APP_ENV.REACT_MCT_API_BASE;
export const APP_CLUSTER = APP_ENV.REACT_APP_CLUSTER;
export const SOL_CLUSTER = APP_ENV.REACT_SOL_CLUSTER;
export const SOL_DELEND_PROGRAM = APP_ENV.REACT_SOL_DELEND_PROGRAM;
